### ISSUE TITLE
Enhancement to this example: to use configuration file for common configuration

### ISSUE THREAD

**Issue by mcuee** [sminez/my-penrose-config#2]
Firstly I will say actually this example config is very usable and I can use it without major problems. Thanks for the great work. I need only to do minor changes to get it working for my daily usages on a Raspberry Pi 400 running Manjaro 64bit ARM version. 
1) cargo.toml --> change directory name
2) lib.rs --> change monitor configuration
3) main.rs --> change key bindings
4) minor changes for the scripts

Just wondering if it is possible for 2) and 3) to be in a configuration file, say in ".config/penrose/config" like other tiling windows managers.

**Comment by sminez** [comment]
I'm afraid that this is just my personal config (as stated in the readme). It is intended as a reference of what a "full" use of Penrose looks like, not a template that can be used directly by others :smile:

You are more than welcome to fork / steal whatever you find interesting for your own config :+1:
